// src/app/layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "./providers";
const NavBar = dynamic(() => import("./components/NavBar"));
import { AuthWrapper } from "./components/AuthWrapper";
import dynamic from "next/dynamic";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Master's Dissertation Management System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <AuthWrapper>
            <div style={{ display: "flex" }}>
              <NavBar />
              <main style={{ flexGrow: 1, padding: "20px", marginTop: "64px" }}>
                {children}
              </main>
            </div>
          </AuthWrapper>
        </Providers>
      </body>
    </html>
  );
}
